apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: minio.minio:9000
      insecure: true
      accessKeySecret:
        name: minio-secret
        key: accessKey

      secretKeySecret:
        name: minio-secret
        key: secretKey
  containerRuntimeExecutor: pns
  metricsConfig: |
    disableLegacy: true
    enabled: true
    path: /metrics
    port: 9090
  # persistence: |
  #   connectionPool:
  #     maxIdleConns: 100
  #     maxOpenConns: 0
  #     connMaxLifetime: 0s
  #   nodeStatusOffLoad: true
  #   archive: true
  #   archiveTTL: 7d
  #   postgresql:
  #     host: postgres
  #     port: 5432
  #     database: postgres
  #     tableName: argo_workflows
  #     userNameSecret:
  #       name: argo-postgres-config
  #       key: username
  #     passwordSecret:
  #       name: argo-postgres-config
  #       key: password
